service: coworker-api

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-central-1

plugins:
  - serverless-offline
  - serverless-jest-plugin

functions:
  auth:
    handler: auth.handler
    events:
      - http:
          path: auth
          method: get   
          request:
            parameters:
              querystrings:
                url: true
      - http:
          path: auth
          method: post
          # cors: true

  hello:
    handler: hello.handler
    events:
      - http:
          path: hello
          method: get
          authorizer:
            name: authorizer
            resultTtlInSeconds: 300
            identitySource: method.request.header.Authorization
            type: token

  authorizer:
    handler: authorizer.handler
